### ISSUE TITLE
Fix random roll timers to allow for multiple roll ranges

### ISSUE THREAD

**Issue by XDharkonX** [EJWellman/QuarmTool#19] opened 2024-05-19 14:29 UTC
Currently the random roll trigger only sets a trigger for the end of the random generation.  If people were rolling from 0- 100 and another person rolled from 99-100 instead, the timer shows the result in the same pane, does not account for incorrect random rolls.  It only filters rolls for the end number of the roll.

**Comment by EJWellman** [comment] 2024-05-20 04:46
Oooh, interesting!
I'll take a look at that.

**Comment by EJWellman** [comment] 2024-05-24 03:40
Sorry for the delay, but I'm actually not able to reproduce this.

![image](https://github.com/EJWellman/QuarmTool/assets/30203270/a9524319-4b24-4b18-bd1b-a557889fd194)
![image](https://github.com/EJWellman/QuarmTool/assets/30203270/148529f3-0bf2-4a63-98e0-2c4fda9eddae)

Can you send me a screenshot of it?

**Comment by Celedh** [comment] 2024-05-25 15:34
I wasn't able to reproduce this either, and even randoms without the minimum value correctly display in the same random group as those that specify a 0 minimum (i.e. random 555 is grouped with random 0 555, while random 545 555 is in a different group showing the 545 min)

**Comment by XDharkonX** [comment] 2024-05-26 14:03
![tes1](https://github.com/EJWellman/QuarmTool/assets/168911365/b075e172-f296-485b-8d99-5882d47a905d)
![test1t](https://github.com/EJWellman/QuarmTool/assets/168911365/814d310a-bd4d-4860-885e-92239f13be03)

Ill update to current version and see if its been fixed somehow there.

**Comment by XDharkonX** [comment] 2024-05-26 14:20
![test13](https://github.com/EJWellman/QuarmTool/assets/168911365/eb7b00d0-31fa-4904-a621-116ab0916601)

**Comment by EJWellman** [comment] 2024-05-27 04:13
Oooh, interesting!
Looking at it now.

**Comment by EJWellman** [comment] 2024-05-27 04:20
It'll be fixed in the next release.
I'd forgotten that I'd made a change to it a while back, and didn't propagate the change over.
Whoops!

**Closed** 2024-05-27 04:23 UTC
Labels: bug
